### ISSUE TITLE
Parakeet

### ISSUE THREAD

**Issue by arita37** [iskandr/parakeet#29]
Hi,

Just wondering why Parakeet was abandonned, since the performance
look very nice.

I have some questions too.
Thanks, regards

**Comment by iskandr** [comment]
Hey arita37,

There are several reasons I stopped working on Parakeet, the most important
of which is probably that there was no scalable path to supporting a larger
subset of Python. The few NumPy operators that worked had to be manually
reimplemented in terms of data parallel operators. Reimplementing all of
NumPy (and maybe SciPy) by myself was a daunting and hopeless endeavor.
Parakeet was always doomed to support only a small and poorly defined
subset of Python.

Additionally, I got interested in biology and work in the Hammerbacher lab
on immunology/oncology/genomics, so I don't have much time left for
debugging a big messy compiler.

I think that if I were to try something like Parakeet again (which I've
considered in light of Wes M's recent work on Arrow and Feather) I would
probably target a single higher level backend (maybe something like
TensorFlow) and only compile expressions built directly by the user code
(not try to pretend to be NumPy).

Another thing that I didn't appreciate when working on Parakeet is that
Theano (and now TensorFlow) actually fill this niche fairly effectively.
Yes, you don't get magical compilation of code that looks unaltered from
Python but you also don't have to contend with the blackbox failures that
accompany dead-end approaches like Parakeet (& Numba, and anything else
that pretends to be Python by reimplementing it).


Cheers,
Alex
