### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by alexbw** [iskandr/parakeet#30]
Heya, just ran across this library, which seems abandoned, but FYI the website for the repo seems unrelated to the repo itself. Might want to update or delete the reference.

**Comment by LucasSilvaFerreira** [comment]
Hi! Alex this is Lucas from Miami.
I was surfing around your  repositories with a friend in my lab and I found the same problem.
The link goes to a porn site! I think is a good  idea remove the link.

Best regards

**Comment by alexbw** [comment]
yikes. @iskandr, this is not good! you should fix it!

**Comment by iskandr** [comment]
YIKES!

Thanks for letting me know.

**Comment by iskandr** [comment]
I think I got all the links, thanks everyone.
